trigger:
  tags:
    include:
      - v.*
  branches:
    include:
      - develop
      - master
  paths:
    exclude:
      - README.md

pr:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  repository: 'focal-freedom-236620/rushcontroller'
  type: $(Build.SourceBranchName)
  commit: $(Build.SourceVersion)
  sem_tag:

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npm test
    displayName: 'unit tests'

  - script: |
      echo "npm test"
    displayName: 'integration tests'

  - task: Docker@2
  - bash: |
      echo current tag..
      sem_tag=$(type)
      sem_tag=${sem_tag:0:3}
      '##vso[task.setvariable variable=sem_tag]$sem_tag'
    displayName: 'tag'
    name: setvarStep
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')

  - bash: |
      echo $sem_tag
    displayName: 'tag'

  - task: Docker@2
    inputs:
      containerRegistry: 'Edgeworx GCP'
      repository: $(repository)
      command: 'buildAndPush'
      tags: |
        $(type)
        $(commit)
        latest
        $(sem_tag)

  - script: |
      echo "npm test"
    displayName: 'api tests'
